- nzpy/core.py
Problem: Query containing interval datatype failed to return result if any of year/month/day/hour/min/sec was 0. For e.g. : 0 years 11 days 21 hours  1 seconds, 20 years 67 days 0 hours 5 minutes 10 seconds.
Solution: Added a default value of zero for year/month/day/hour/min/sec
Testing: Ran a query for different value of interval datatype
> Fix to add default value for interval datatype

- nzpy/core.py
Issue link: https://github.com/IBM/nzpy/issues/6
Problem: Error/exception is not reset for multiple execute 
Solution: Reset the error/exception for every execute statement
Testing: Tested by executing multiple execute statement where one of them throws exception
> Fix to clear error/exception for multiple execute statement

- nzpy/core.py
Issue:https://github.com/IBM/nzpy/issues/13
Problem: Incorrect values returned when selecting NULL values from a user table. Bytes of data from backend which determines null columns was interpreted wrongly. 
Solution: Instead of reading all bytes and converting it to binary, read byte by byte and convert each byte to binary and append in a list
Testing: Ran a sample app that fetch mix of NULL and non NULL values. Ran nzpy testsuite.
> Fix to fetch values correctly while selecting NULL values

- nzpy/core.py
Issue:https://github.com/IBM/nzpy/issues/9
Problem: ANALYZE flag is appended to non select query incorrectly as the condition checks if query contains 'select' keyword. 
Solution: Instead of checking condition that query contains 'select' keyword, it should check if query starts with 'select' keyword.
Testing: Ran a sample application with query containing 'select' keyword like 'create view user_v as select * from t1' and create external table query. Ran nzpy testsuite.
> Fix to prevent ANALYZE flag from being appended in non select query

- nzpy/core.py
Issue:https://github.com/IBM/nzpy/issues/8
Problem: Parameter marker doesn't work with type None 
Solution: Added a check that if argument is None, replace it with NULL in the query
Testing: Ran a sample app with parameter marker as None for all datatypes. Ran nzpy testsuite.
> Fix to support parameter marker with type None

- nzpy/__init__.py
- nzpy/core.py
Issue: https://github.com/IBM/nzpy/issues/7
Problem: Char/varchar data type does not supports the ISO Latin-9 code set
Solution: Now user can provide encoding for char/varchar datatype from application. Default value is 'latin'
Testing: Ran sample application with char, varchar datatype containing latin char. Ran nzpy test suite.
> Fix to support latin-9 code set for char/varchar datatype

- README.md
Issue: https://github.com/IBM/nzpy/issues/16
Problem: nzpy should show recommended python scoping syntax for conn.cursor
Solution: Change the document to show scoping syntax. cursor.close() is already documented in https://www.python.org/dev/peps/pep-0249/
Testing: NA
> Document changes: NZPY should show recommended python syntax examples

- README.md
Remove NPS hostname vmnps-dw10.svl.ibm.com from README.md
> Remove NPS hostname from README.md

- nzpy/core.py
The attached changes fixes an error in the relevant code path wherein the variable `length` is not defined and, instead, should be `len` according to the scope.
> Fixing undefined variable error

- README.md
- nzpy/core.py
JIRA: https://github.com/IBM/nzpy/issues/24
Problem: Notices should be accessible via the cursor, not via the connection
Solution: Notices are stored in deque in cursor class. User can access notices using the cursor object.
Testing: 
```
DB1.ADMIN(ADMIN)=> CREATE or replace PROCEDURE  CUSTOMER() RETURNS INTEGER LANGUAGE NZPLSQL AS BEGIN_PROC BEGIN RAISE NOTICE 'The customer name is alpha'; RAISE NOTICE 'The customer location is beta'; END; END_PROC;
CREATE PROCEDURE
In application:
with conn.cursor() as cursor:
cursor.execute("call CUSTOMER();")
for notice in cursor.notices:
print(notice)
NOTICE: The customer name is alpha
NOTICE: The customer location is beta
```
> Fix to access notices via the cursor

- nzpy/core.py
JIRA: https://github.com/IBM/nzpy/issues/33
Problem:When query receives an error from backend(i.e. backend response 'E'), after processing error we are not consuming response 'Z' from backend. These bytes remain on socket and causes reading incorrect data for next query and thereby causing nzpy to hang.
Solution: After handling character 'E' from backend continue listening to backend for 'Z' and consume the response.
Testing: Issue happened when running nzbatchbnr testcase or nzalchemy+nzpy testcase. After fix, ran same testcase and issue was not observed.
> Fix nzpy query hang issue: handle 'Z' after error

- nzpy/handshake.py
JIRA: https://github.com/IBM/nzpy/issues/39
Problem: It is observed that in some cases, nzpy hangs if backend sends notice just after handshake/connection setup completion. For e.g: due to some issue in system, a notice is sent everytime nzsql is fired.
```
[nz@ipshost-0 nzbatchbnr_test]$ nzsql -l
NOTICE:  SET PATH: unable to locate the schema / database 'SQLEXT'
List of databases
DATABASE   | OWNER
--------------+-------
SYSTEM       | ADMIN
TPCDS100_BNR | ADMIN
(2 rows)
```
Solution: Handle notice 'N' from backend in conn_connection_complete() and log the notice. 
Testing: Tested this on system where the above problem was observed. After fix, this issue was not observed. 
Ran nzpy testcase.
> Fix to handle backend notices just after connection completes

- nzpy/core.py
JIRA: https://github.com/IBM/nzpy/issues/37
Problem: 
nzpy returns Incorrect timestamp for below data in table :
```
DB1.ADMIN(ADMIN)=> select * from date_Table;
ID |         DATE_DATA
----+----------------------------
2 | 2012-10-15 12:57:18.000396
```
nzpy returns :
```
[nz@sim-ips26 python]$ python3 run4.py
['2012-10-15 12:57:18.396']
```
Solution: 
1. Added zero padding before microsec
2. Removed unwanted code "fraction *= 1000"
3. In few cases, dt param in timestamp2struct() is negative which calculates wrong date. Corrected division there.  
Testing: Ran above test case. Ran nzpy testcases and nzalchemy+python testcases.
> Fix to return correct microsec for timestamp datatype

- nzpy/core.py
- tests/test_functional.py
- tests/test_typeconversion.py
JIRA: https://github.com/IBM/nzpy/issues/35
Problem: Nzpy throws error when using python datetime type as placeholder . For e.g:
```
import nzpy
from datetime import ( datetime as Datetime)
conn = nzpy.connect(user="admin", password="password",host='localhost', port=5480, database="db1", securityLevel=0,logLevel=0, logOptions=nzpy.LogOptions.Logfile)
with conn.cursor() as cursor:
v = Datetime(2001, 2, 3, 4, 5, 6, 170000)
cursor.execute("select ? as f1",(v,))
for i in cursor.fetchall():
print(i)
```
Solution: 
1. Add change in Prepare() to check if columns type is instance of date, time or datetime.
2. Added change to check if no placeholder in query then ANALYZE flag should not be added.
Testing:  Ran sample application where error observed. Ran nzpy test suite.
> Fix error when using python datetime type as placeholder

- README.md
- nzpy/core.py
- tests/test_typeconversion.py
JIRA: https://github.com/IBM/nzpy/issues/42
Problem: Two new datatypes are introduced in NPS: JSON and JSONB. The support of these two datatypes on the server-side requires some changes on the client-side so it can retrieve JSON/JSONB data from the server. 
Solution:
1. Enabling nzpy client to send its client version string 'Release 11.1.0.0' to the server at the beginning of each session, which tells the server that nzpy client is capable of handling JSON/ JSONB data. Notice: the client version string must start with a string, such as 'Release', in order for the server to properly parse it.
2. Mapping JSON/JSONB data to string type in nzpy, which can be handled in a similar fashion as NVARCHAR data in nzpy.
Testing: Ran an application which fetches JSON and JSONB datatypes. Results …
> Fix to support JSON/JSONB/JSONPATH datatypes

- nzpy/__init__.py
- nzpy/core.py
- nzpy/handshake.py
Add code for passing pgoptions when establishing a database connection
Testing:
- Tried to do testing with python2, but there seems to be sytax errors unrelated to my changes
- Tested with python3...one failed test, but seems unrelated 'FAILED test_typeconversion.py::test_xml_roundtrip - nzpy.core.ProgrammingError: ERROR:  Function 'XMLPARSE(UNKNOWN)' does not exist'
- Used interactive python shell to ensure that my pgoption was passed, and the effect was correctly taken by the database
> Add a way to pass pgoptions when establishing the connection

- nzpy/core.py
Fixes https://github.com/IBM/nzpy/issues/54
Test:
before: fetchone() would return next of unconsumed resultset of prior query.
now:
```
>>> with nzpy.connect(user="admin", password="password", host="localhost", port=5480, database="db1") as conn:
...     with conn.cursor() as curs:
...             curs.execute("Select * from t1")
...             curs.description
...             curs.fetchone()
...             curs.execute("select * from _v_Database")
...             curs.description
...             curs.fetchone()
... 
<nzpy.core.Cursor object at 0x7ff728466da0>
(('OBJID', 23), ('OBJNAME', 2530))
[5006, '_T_OBJECT']
<nzpy.core.Cursor object at 0x7ff728466da0>
(('OBJID', 26), ('DATABASE', 19), ('OWNER', 19), ('CREATEDATE', 702), ('DB_CHARSET', 19), ('DB_COLLATION', 19), ('DBCHARSET', 26), …
```
> clear cursor before execute

- nzpy/handshake.py
Log messages shown during nzpy connection establishment are in bytes.
Database name log message is not showing database name.
```
DEBUG:nzpy.Connection[db1]:Database name: db1
INFO:nzpy.Connection[db1]:Backend response: N
DEBUG:nzpy.Connection[db1]:Security Level requested = 1
DEBUG:nzpy.Connection[db1]:Got response =b'N'
DEBUG:nzpy.Connection[db1]:Attempting unsecured session
DEBUG:nzpy.Connection[db1]:Connection protocol set to : 3 5
INFO:nzpy.Connection[db1]:Backend response: N
INFO:nzpy.Connection[db1]:Backend response: N
INFO:nzpy.Connection[db1]:Backend response: N
INFO:nzpy.Connection[db1]:Backend response: N
INFO:nzpy.Connection[db1]:Backend response: N
INFO:nzpy.Connection[db1]:Backend response: N
DEBUG:nzpy.Connection[db1]:Got response: b'R'
DEBUG:nzpy.Connection[db1]:auth got …
```
> Fixing logs related to connection establishment

- nzpy/__init__.py
- nzpy/core.py
- nzpy/handshake.py
- tests/conftest.py
- tests/test_connection.py
- tests/test_dbapi.py
- tests/test_dbapi20.py
- tests/test_functional.py
- tests/test_logging.py
- tests/test_paramstyle.py
- tests/test_query.py
- tests/test_typeconversion.py
- tests/test_typeobjects.py
Issue: https://github.com/IBM/nzpy/issues/41
Performed flake8 analysis on nzpy and fixed the errors
```
python3 ./nzpy_test.py 
Table customerAddress created successfully
1 rows inserted
1 rows inserted
1 rows inserted
Id = 1
Name = Jack
Address = High street, London
Email = jack4321@ibm.com
Table customerData created successfully
1 rows inserted
1 rows inserted
1 rows inserted
Id = 2
FirstName = Tom
LastName = Banks
Age = 28
Address = Park street, NY
Email = tom1234@ibm.com
Table row count is [3]
Create external table created successfully
External Table loaded successfully
After load from External Table, table row count is [6]
```
> flake8 modifications

- tests/test_connection.py
- tests/test_dbapi.py
- tests/test_dbapi20.py
- tests/test_typeconversion.py
Problem:
Some of the testcases for nzpy were not working properly.
Solution:
Fixed the syntax to make it work.
Testing:
Run command `pytest-xv` to test
> Nzpy testcases fix

- nzpy/handshake.py
Problem:
The code in handshake.py for creating sslcontext was deprecated.
Solution:
Updated the code to remove deprecation warnings.
Test:
Create a secure ssl connection to nps using nzpy by providing the cacert.pem file .
Before fix
```
python3 test.py
/Users/ayush/Desktop/teempnapy/venv/lib/python3.12/site-packages/nzpy/handshake.py:269: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
self._usock = ssl.SSLContext().wrap_socket(self._usock)
/Users/ayush/Desktop/teempnapy/venv/lib/python3.12/site-packages/nzpy/handshake.py:269: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
self._usock = ssl.SSLContext().wrap_socket(self._usock)
Connection to nzpy successful
```
After Fix
```
python3 test.py
Connection to nzpy successful
```
> Fix for deprecation warnings
